#Robocode Compiler Properties
#Fri Aug 28 15:29:32 GMT-03:00 2026
compiler.binary=
compiler.classpath=-classpath libs\\robocode.jar;"C\:\\Licenciatura en Informatica\\Cuarto Anho\\Segundo Cuatrimestre\\Laboratorio de software\\RobocodeLabo-1.11.1\\RobocodeLabo\\robots"
compiler.options=
robocode.version=1.11.1
