#Robocode window sizes
#Mon Sep 14 20:48:28 GMT-03:00 2026
net.sf.robocode.ui.dialog.ConsoleDialog=518,231,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=170,92,842,651
net.sf.robocode.ui.dialog.PreferencesDialog=320,284,894,294
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,927,701
net.sf.robocode.ui.editor.RobocodeEditor=386,126,764,611
