#Robocode window sizes
#Sun Aug 30 14:10:47 GMT-03:00 2026
net.sf.robocode.ui.dialog.ConsoleDialog=518,231,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=170,92,842,651
net.sf.robocode.ui.dialog.RobocodeFrame=-7,-7,927,701
net.sf.robocode.ui.editor.RobocodeEditor=386,126,764,611
